### ISSUE TITLE
Algorithm constraints check failed on signature algorithm: SHA1withRSA

### ISSUE THREAD

**Issue by backwind1233** [azure-javaee/rhel-jboss-templates#2]
https://learn.microsoft.com/en-us/azure/mysql/flexible-server/how-to-connect-tls-ssl

## Context
JBoss EAP: EAP8
JDK:          JDK17

Error stack

```
Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1568)
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1493)
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1437)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
... 61 more
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA1withRSA
at java.base/sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:237)
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1564)
... 64 more
```

## RCA:

1. Azure MySQL Flexible server root CA use algorithm: SHA1withRSA, but the algorithm has been deprecated since JDK9.
2. This caused `Algorithm constraints check failed on signature algorithm: SHA1withRSA` error when using jbdc to connect Azure MySql Flexible server in JDK17

## Actions to do -If SHA-1 is a current blocker

1. Follow the [instructions](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-root-certificate-rotation)  for creating a combined CA certificate on the client
2. Open a support request to rotate your Azure Database for MySQL – Flexible Server root CA.

**Comment by backwind1233** [comment]
same issue https://github.com/keycloak/keycloak/issues/32248

**Comment by edburns** [comment]
Here is an undesirable workaround: https://github.com/keycloak/keycloak/issues/30164#issuecomment-2268885498 . See also this comment https://github.com/keycloak/keycloak/issues/30164#issuecomment-2666021197.

**Comment by backwind1233** [comment]
See also 
- [postgresql error connect with Algorithm constraints check failed on signature algorithm: SHA1withRSA](https://github.com/dbeaver/dbeaver/issues/20856)

**Comment by backwind1233** [comment]
A [workaround](https://github.com/dbeaver/dbeaver/issues/20856#issuecomment-1676225708) to this issue.
